#%RAML 1.0
title: MuleSoft Accounts API

/accounts:
  get:
    queryParameters:
      source:
        required: true

      accountType:
        required: false

      name:
        required: false

    responses:
          200:
            body:
              application/json:
                examples: !include examples/AccountsExample.raml

  post:
    queryParameters:
      source:
        required: true

    body:
      application/json:
        type: AmericanFlight
        examples:
          input: !include /examples/AccountsNoIDExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Flight added (but not really)
        
                  
