#%RAML 1.0
title: MuleSoft Accounts API

/accounts:
  get:
    queryParameters:
      source:
        required: true

      accountType:
        required: false

      name:
        required: false

    responses:
          200:
            body:
              application/json:
                examples: !include examples/AccountsExample.raml

  post:
    queryParameters:
      source:
        required: true
        
                  
