#%RAML 1.0 NamedExample
value:
  
  - 
    ID: 1 
    Name: John
    Type: personal
    Address: 12345 Green St,Boulder,Colorado,82433,USA
    AirMiles: 100
    CreationDate: 2017/07/27
  - 
    ID: 2 
    Name: SAP
    Type: business
    Address: 5432 Brown St,Boulder,Colorado,82463,USA
    AirMiles: 5000
    CreationDate: 2018/08/28